controller_manager:
  ros__parameters:
    update_rate: 200  # Hz
    
    # Controllers to load
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    cart_controller:
      type: pid_controller/PidController

# Controller-specific parameters
joint_state_broadcaster:
  ros__parameters:
    joints:
      - cart_joint
      - pole_joint

cart_controller:
  ros__parameters:
    dof_names:
      - cart_joint
    reference_and_state_interfaces:
      - position
    command_interface:
      - position
    gains:
      cart_joint:
        p: 30.0
        i: 24.0
        d: 2.0
        i_clamp_max: 10.0
        i_clamp_min: -10.0